### ISSUE TITLE
Characteristics of buzzer

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/adi-buzzer#13]
Identify the chars of buzzer

**Comment by AndhikaS97** [comment]
some of the buzzers retweeting a lot on the current political issue.

**Comment by andreaschandra** [comment]
- discussing politics only as a buzzer
- using rude words, abusive, and tendentious
without necessarily using hashtag, usually found on replies to another tweet
@AndhikaS97

**Comment by AndhikaS97** [comment]
There are 3 types of buzzer:
Focusing on social issues
- Activist (ex. Lini ZQ, Veronica)
- Influencer (ex. Cania)
- Politician (ex. Fadli Zon)

Definitions of the buzzer that we are tagging on:
An account that specifically tweets or retweets to fulfill a political agenda.
Using BOTS:
- Only retweeting focused and happening political issues
- Username contains numbers (ex. Andhika99911)
- Have a pattern regarding their tweets (using the same hashtag all over the tweets)

Unidentified User:
- Tweet and retweet focused and happening political issues
- The username is more natural than bots
- Not using the hashtag to provoke
