### ISSUE TITLE
EDA labeled account

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/adi-buzzer#19]
boundaries yang jelas antara buzzer dan non buzzer
kalo pake rule based mungkin bakal:
- banyak tweet dari suatu account yang pake hashtag, e.g 80% dari tweetnya pake hashtag
- banyak retweet yang mengandung hashtag atau yang bermuatan politik entah berupa text, gambar atau video
- Jika tidak menggunakan hashtag, tidak meretweet, namun sering membuat tweet yang me-mention tokoh-tokoh politik dan sangat sering e.g 70% of the tweets

Task:
- [x] average tweet per hari (assumsi: buzzer lebih sering ngetweet per hari)
- [x] average retweet per hari (asumsi: buzzer lebih sering retweet per hari)
- [x] average hashtag yang dipake dalam suatu tweet (asumsi: tweet buzzer punya lebih banyak hashtag di tweetnya)
- [x] average tweet yang pake hashtag (asumsi: buzzer lebih sering pake hashtag tiap membuat tweet)
- [x] bikin kategori hashtag dictionary (politik / non politik)
- [ ] probability hashtag politik yang dipakai per account

**Comment by andreaschandra** [comment]
Average tweets per account
![average-tweets-per-account](https://user-images.githubusercontent.com/13943428/96610085-6ee2b100-1325-11eb-8fb6-00d73b1348cf.png)

average retweet dari total tweet
![average_rt_per_account](https://user-images.githubusercontent.com/13943428/96617213-89208d00-132d-11eb-90b8-802ce88ede57.png)

average hashtag per user
![average_hashtag_per_user](https://user-images.githubusercontent.com/13943428/96617302-a5bcc500-132d-11eb-9b18-27eea687422a.png)

average tweet contains hashtag
![average_tweet_contain_hashtag](https://user-images.githubusercontent.com/13943428/96617334-b2411d80-132d-11eb-9610-6358a13fd6d3.png)

**Comment by andreaschandra** [comment]
Dictionary hashtag yang perlu di label
https://drive.google.com/file/d/1ggzzbHiz5cKXct7xzR_MrKsyVRLJwFjZ/view?usp=sharing

@rubentea16 @AndhikaS97

**Comment by andreaschandra** [comment]
@rubentea16 @AndhikaS97 ini plot dari hashtag yang dilabelin. imbalance

![hashtag_label](https://user-images.githubusercontent.com/13943428/97778570-a6b1ea00-1baa-11eb-9e3e-af6cdece486e.png)

**Comment by AndhikaS97** [comment]
Kalo imbalance gitu gimana? Harus dilanjut labelin lagi kah sampe balance?

**Comment by andreaschandra** [comment]
hmm... coba gw modeling dulu ya, kalo semisal ga perform, either emang susah buat diseperate karena kurang data, atau labelnya yang ga konsisten

**Comment by andreaschandra** [comment]
Baseline
- BernouliNB
![image](https://user-images.githubusercontent.com/13943428/97782464-3c0da800-1bc4-11eb-9ab1-2cbdd0ee96b3.png)

- SVM
![image](https://user-images.githubusercontent.com/13943428/97782483-4def4b00-1bc4-11eb-9ab6-024d562aad4c.png)

- Random Forest
![image](https://user-images.githubusercontent.com/13943428/97782502-68292900-1bc4-11eb-86ed-0652e3f39c9f.png)

- AdaBoost
![image](https://user-images.githubusercontent.com/13943428/97782515-7b3bf900-1bc4-11eb-9daf-7e70ed127846.png)

- Gradient Boosting
![image](https://user-images.githubusercontent.com/13943428/97782538-9c044e80-1bc4-11eb-87d8-3ea07be13298.png)

**Comment by andreaschandra** [comment]
## Update trigram character
![image](https://user-images.githubusercontent.com/13943428/99247353-6a80b980-2839-11eb-80bc-efeabae32965.png)
![image](https://user-images.githubusercontent.com/13943428/99247378-73718b00-2839-11eb-8012-385bca63d0bc.png)
![image](https://user-images.githubusercontent.com/13943428/99247425-85ebc480-2839-11eb-8622-01d8ab6ac3bc.png)
![image](https://user-images.githubusercontent.com/13943428/99247444-8e43ff80-2839-11eb-9d79-4ece5ce8a221.png)
![image](https://user-images.githubusercontent.com/13943428/99247462-9439e080-2839-11eb-8736-cee70b41591b.png)

**Comment by andreaschandra** [comment]
close eda ya guys @AndhikaS97 @rubentea16
